### ISSUE TITLE
listing-2.js not included in repo

### ISSUE THREAD

**Issue by rgdonohue** [JavaScript-Data-Wrangling/Chapter-3#1]
Is cited in the book, however.

https://livebook.manning.com/#!/book/data-wrangling-with-javascript/chapter-3/v-2/68

I see now that many of the listings are included. Perhaps intentional.

**Comment by ashleydavis** [comment]
Hi Rich,

There is actually code for this listing, it's just probably not obvious where it is. 

This is the file: https://github.com/Data-Wrangling-with-JavaScript/Chapter-3/blob/master/toolkit/file.js

I'm going to update the text to make it more obvious where to find the code.

Thanks for your help!
