### ISSUE TITLE
semicolin breaks method chaining in listing-4.js

### ISSUE THREAD

**Issue by rgdonohue** [JavaScript-Data-Wrangling/Chapter-3#2]
Need to remove the semicolon on line 4

![image](https://user-images.githubusercontent.com/1952205/39068590-057a4e96-449a-11e8-96bb-58cb1167a7c3.png)

**Comment by ashleydavis** [comment]
Hi Rich, thanks for reporting the issue.

I've fixed it in the text and the fix will come through in the next MEAP update (probably in a month or so).

Thanks!
