### ISSUE TITLE
Need to limit search results for listing-3.12 to avoid "400 Error" 

### ISSUE THREAD

**Issue by sestaton** [JavaScript-Data-Wrangling/Chapter-3#4]
If you run `listing-3.12.js` as is you'll get:

    { StatusCodeError: 400 - "Error 400: Bad Request\n\n20160 matching events exceeds search limit of 20000. Modify the search to match fewer events.\n\nUsage details are available from https://earthquake.usgs.gov/fdsnws/event/1\n\nRequest:\n/fdsnws/event/1/query.csv?starttime=2017-01-01&endtime=2017-03-02\n\nRequest Submitted:\n2019-01-23T22:45:30+00:00\n\nService version:\n1.7.0"

This is because the API has a [defined limit](https://earthquake.usgs.gov/fdsnws/event/1/) on the number of items that can be returned (20k). If we limit the number of items in the request it will avoid the issue, and this can be done by changing the URL on line 4 to:

    const url = "https://earthquake.usgs.gov/fdsnws/event/1/query.csv?starttime=2017-01-01&endtime=2017-03-02&limit=20000";

I could submit a PR if that would help but it's just a one line fix.

Hope this helps.

**Comment by ashleydavis** [comment]
Hey thanks for reporting this issue! If you submit a PR that would
definitely save me some time!

**Comment by sestaton** [comment]
Will do!
